import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "optigarment",
  description: "Generated by create next app",
  icons: {
    icon: "/images/Logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      dir="rtl"
      // className={surt.variable}
    >
      <body>{children}</body>
    </html>
  );
}
